variables:
    SolutionPrefix: 'Dfc.Poc'
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.9.1
    endpoint: 'GitHub (ESFA)'

stages:
- stage: Build
  jobs:
  # ARM template
  - job:
    displayName: "Check ARM templates"
    pool: 'NCS - CI and CD'
    steps:
    - template: /AzureDevOpsTemplates/Build/StepTemplates/dfc-arm-build.yml@dfc-devops
      parameters:
        ArmTemplateRoot: "$(System.DefaultWorkingDirectory)/Resources/ArmTemplates"

  # Web App
  - job:
    displayName: "Build DotNetCore app"
    pool: 'NCS - CI and CD'
    steps:
    - template: /AzureDevOpsTemplates/Build/StepTemplates/dfc-dotnetcore-build-notests.yml@dfc-devops
      parameters:
        SolutionBaseName: "$(SolutionPrefix).WebApp"
        BuildPlatform: $(BuildPlatform)
        BuildConfiguration: $(BuildConfiguration)
        PublishWebApp: true
