parameters:
  Environment: 'Unknown'
  ArmTemplateRoot: ''
  AzureSubscription: ''
  ResourceGroup: ''
  EnvironmentTag: ''
  ParentBusinessTag: ''
  ServiceOfferingTag: 

jobs:
- deployment: Deploy_${{ parameters.Environment }}
  pool:
    name: 'NCS - CI and CD'
  environment: ${{ parameters.Environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        # debug
        - powershell: |
            Write-Output "Endpoint: ${{ parameters.AzureSubscription }}"
            Write-Output "Resource group: ${{ parameters.ResourceGroup }}"
            Write-Output "Env tag: ${{ parameters.EnvironmentTag }}"
            Write-Output "Parent business: ${{ parameters.ParentBusinessTag }}"
            Write-Output "Service: ${{ parameters.ServiceOfferingTag }}"
          displayName: Dummy step
        # ARM template
#        - template: AzureDevOpsTemplates/Deploy/StepTemplates/dfc-arm-deploy.yml@dfc-devops
#          parameters:
#            ArmTemplateRoot: "${{ parameters.ArmTemplateRoot }}"
#            AzureSubscription: "${{ parameters.AzureSubscription }}"
#            ResourceGroup: "${{ parameters.ResourceGroup }}"
#            EnvironmentTag: "${{ parameters.EnvironmentTag }}"
#            ParentBusinessTag: "${{ parameters.ParentBusinessTag }}"
#            ServiceOfferingTag: "${{ parameters.ServiceOfferingTag }}"
