parameters:
  Environment: 'Unknown'
  ArmTemplateRoot: ''
  AzureSubscription: ''
  ResourceGroup: ''
  EnvironmentTag: ''
  ParentBusinessTag: ''
  ServiceOfferingTag: ''
  AppServicePrefix: ''
  WebAppPackage: ''
  FunctionAppPackage: ''

jobs:
# Deploy ARM template
- deployment: AzureResources_${{ parameters.Environment }}
  pool:
    name: 'NCS - CI and CD'
  environment: ${{ parameters.Environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        # ARM template
        - template: AzureDevOpsTemplates/Deploy/StepTemplates/dfc-arm-deploy.yml@dfc-devops
          parameters:
            ArmTemplateRoot: "${{ parameters.ArmTemplateRoot }}"
            AzureSubscription: "${{ parameters.AzureSubscription }}"
            ResourceGroup: "${{ parameters.ResourceGroup }}"
            EnvironmentTag: "${{ parameters.EnvironmentTag }}"
            ParentBusinessTag: "${{ parameters.ParentBusinessTag }}"
            ServiceOfferingTag: "${{ parameters.ServiceOfferingTag }}"

# Deploy web app
- deployment: WebApp_${{ parameters.Environment }}
  pool:
    name: 'NCS - CI and CD'
  dependsOn: AzureResources_${{ parameters.Environment }}
  environment: ${{ parameters.Environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        # Deploy app to slot template
        - template: StepTemplates/dfc-appservice-deploy-slot.yml
          parameters:
            AzureSubscription: "${{ parameters.AzureSubscription }}"
            ResourceGroup: "${{ parameters.ResourceGroup }}"
            AppServiceName: "${{ parameters.AppServicePrefix }}-as"
            Package: "${{ parameters.WebAppPackage }}"
